settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: server
  path: server
  commands:
    generate:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    - graphql
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    # scripts:
    #   - type: before
    #     command: go generate ./graph/graph.go
    #     output: true
